# Use the official PostgreSQL 16 image based on Alpine Linux from Docker Hub
FROM postgres:16-alpine

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=mydatabase

# Expose the PostgreSQL port
EXPOSE 5432
