server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "myapp-logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "myapp"
          __path__: /var/log/myapp*.log

  - job_name: "rustaccount-logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "rustaccount"
          __path__: /var/log/rustaccount*.log.*
