services:
  echocache:
    image: myredis
    ports:
      - "6379:6379"
  echodb:
    image: mypostgres
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  echorabbit:
    image: myrabbit
    ports:
      - "5672:5672"
      - "15672:15672"
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
