version: '3'

#taskfile is used for starting servers and queues

vars:
  GO_DIR: backend/go
  RUST_DIR: backend/rust

tasks:
  start_servers:
    cmds:
      - cd ../../{{.RUST_DIR}}/echo_account && cargo run --bin account_api
    silent: false
  start_queues:
    cmds:
      - cd ../../{{.GO_DIR}}/email && go run main.go
 #     - cd {{.GO_DIR}}/email && go run main.go
    silent: false

